### ISSUE TITLE
Undefined errors

### ISSUE THREAD

**Issue by charlesneimog** [ericlyon/pd-lyonpotpourri#24]
Hi,

I tried to download it from Deken, and I had this error:

```
/home/neimog/Documents/Pd/externals/lyonpotpourri/adsr~.pd_linux:/home/neimog/Documents/Pd/externals/lyonpotpourri/liblyonpotpourri.so: undefined symbol: makewt
lyonpotpourri/adsr~
... couldn't create
/home/neimog/Documents/Pd/externals/lyonpotpourri/samm~.pd_linux:/home/neimog/Documents/Pd/externals/lyonpotpourri/liblyonpotpourri.so: undefined symbol: makewt
lyonpotpourri/samm~ 40 1
... couldn't create

```

Same thing if I try to compile it myself on **Linux**.

**Comment by ericlyon** [comment]
Thank you for the report. I won't have time to investigate until early November. There is a reference to the nonexistent "makewt" function, which was long ago replaced with "lpp_makewt" in the lyonpotpourri code. If you can find a reference to "makewt" in the current code, that could be the problem. But since I've been using a build from the latest codebase for about a year without encountering this problem, I'd be surprised if it's the code. Another thing to try - delete all other lyonpotpourri installations from your system to ensure that you're not unintentionally loading old builds. Please report any progress.

Thanks!
Eric
